# Generated by Django 5.2.8 on 2026-01-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='calories',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
