# Generated by Django 5.2.8 on 2026-01-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_receipe_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='quantity',
            field=models.FloatField(default=1.0),
        ),
    ]
