# Generated by Django 5.2.8 on 2026-01-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_grocery_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='carbs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='fats',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='protein',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
