# Generated by Django 5.2.8 on 2026-01-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_receipe_carbs_receipe_fats_receipe_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='unit',
            field=models.CharField(default='unit', max_length=20),
        ),
    ]
