# Generated by Django 5.2.8 on 2026-01-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_grocery_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='grocerie_type',
            field=models.CharField(choices=[('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Dairy', 'Dairy'), ('Meat', 'Meat/Fish'), ('Grains', 'Grains/Pasta'), ('Spices', 'Spices'), ('Beverages', 'Beverages'), ('Snacks', 'Snacks'), ('Others', 'Others')], default='Others', max_length=50),
        ),
        migrations.DeleteModel(
            name='GroceryType',
        ),
    ]
