# Generated by Django 5.0.1 on 2026-02-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_alter_grocery_grocerie_type_delete_grocerytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='grocerie_type',
            field=models.CharField(choices=[('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Dairy', 'Dairy'), ('Meat', 'Meat/Fish'), ('Grains', 'Grains/Pasta'), ('Spices', 'Spices'), ('Condiments & Seasonings', 'Condiments & Seasonings'), ('Beverages', 'Beverages'), ('Snacks', 'Snacks'), ('Others', 'Others')], default='Others', max_length=50),
        ),
    ]
