# Generated by Django 5.0.1 on 2026-02-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_grocery_manufacturing_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
