# Generated by Django 5.0.1 on 2026-02-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_receipe_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='cooking_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
